runtime: php82  # Or php80 for PHP 8.0, php81 for PHP 8.1, etc.
env: flex

# The instance class determines the amount of CPU and memory for each instance
instance_class: F2

# Set the entry point of the application
entrypoint: serve public/index.php --port 8080

# Optional: Set environment variables
env_variables:
  APP_ENV: production
  APP_DEBUG: false
  APP_KEY: base64:YOUR_APP_KEY
  DB_CONNECTION: mysql
  DB_HOST: YOURDATABASE
  DB_PORT: 3306
  DB_DATABASE: YOURDATABASE
  DB_USERNAME: YOURDATABASE
  DB_PASSWORD: YOURDATABASE

# Configure handlers
handlers:
- url: /.*
  script: auto

